deltaG: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-dGinput-GConly-current.tsv
exclude: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-exclude-GConly-current.tsv
#deltaG: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-dGinput-GConly-original.tsv
#exclude: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-exclude-GConly-original.tsv 
transporters: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-TMFA_transporter.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/concentration-bounds_DG25.tsv
concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/concentration-bounds_516v2.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/concentration-bounds_516v2_NH4-24.11.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/concentration-bounds_516v3.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-TMFA_medium.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-TMFA_medium-changeH2conc.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-TMFA_medium_DG25_ori.tsv
#concentrations: /data4/kzhang/Cbescii/Data/Cbes-TMFA-NEW/tmfa-inputs/input_files/cbes-TMFA_medium_DX25_ori.tsv
proton-in: C00080[c]
proton-out: C00080[e]
water:
  - C00001[c]
  - C00001[e]

